DELETE FROM author_commit
WHERE (project_id = 'org.apache:archiva' AND author = 'Carlos Sanchez Gonzalez')
   OR (project_id = 'org.apache:archiva' AND author = 'Emmanuel Venisse')
   OR (project_id = 'org.apache:archiva' AND author = 'Jevica Arianne B. Zurbano')
   OR (project_id = 'org.apache:archiva' AND author = 'Marecor M. Baclay')
   OR (project_id = 'org.apache:batik' AND author = 'Bella Robinson')
   OR (project_id = 'org.apache:bcel' AND author = 'Chas Honton')
   OR (project_id = 'org.apache:bcel' AND author = 'Conor MacNeill')
   OR (project_id = 'org.apache:bcel' AND author = 'David Dixon-Peugh')
   OR (project_id = 'org.apache:bcel' AND author = 'Gary D. Gregory')
   OR (project_id = 'org.apache:bcel' AND author = 'Jason van Zyl')
   OR (project_id = 'org.apache:bcel' AND author = 'Mark Emlyn David Thomas')
   OR (project_id = 'org.apache:bcel' AND author = 'Mark Thomas')
   OR (project_id = 'org.apache:bcel' AND author = 'Markus Dahm')
   OR (project_id = 'org.apache:beanutils' AND author = 'Geir Magnusson Jr')
   OR (project_id = 'org.apache:beanutils' AND author = 'Henri Yandell')
   OR (project_id = 'org.apache:beanutils' AND author = 'James Strachan')
   OR (project_id = 'org.apache:beanutils' AND author = 'Oliver Heger')
   OR (project_id = 'org.apache:beanutils' AND author = 'Rodney Waldhoff')
   OR (project_id = 'org.apache:beanutils' AND author = 'Stian Soiland-Reyes')
   OR (project_id = 'org.apache:beanutils' AND author = 'Vadim Gritsenko')
   OR (project_id = 'org.apache:cayenne' AND author = 'Michael Ray Gentry')
   OR (project_id = 'org.apache:cocoon' AND author = 'Anthony Collen')
   OR (project_id = 'org.apache:cocoon' AND author = 'Bernhard Huber')
   OR (project_id = 'org.apache:cocoon' AND author = 'David Crossley')
   OR (project_id = 'org.apache:cocoon' AND author = 'Gregor Rothfuss')
   OR (project_id = 'org.apache:cocoon' AND author = 'Lars Trieloff')
   OR (project_id = 'org.apache:cocoon' AND author = 'Nicola Ken Barozzi')
   OR (project_id = 'org.apache:cocoon' AND author = 'Ralph Goers')
   OR (project_id = 'org.apache:cocoon' AND author = 'Timothy D. Larson')
   OR (project_id = 'org.apache:codec' AND author = 'Henri Yandell')
   OR (project_id = 'org.apache:codec' AND author = 'Jochen Wiedmann')
   OR (project_id = 'org.apache:codec' AND author = 'Julius Davies')
   OR (project_id = 'org.apache:codec' AND author = 'Stefan Bodewig')
   OR (project_id = 'org.apache:codec' AND author = 'Thomas Neidhart')
   OR (project_id = 'org.apache:collections' AND author = 'Arron Claude Bates')
   OR (project_id = 'org.apache:collections' AND author = 'Craig R. McClanahan')
   OR (project_id = 'org.apache:collections' AND author = 'Dipanjan Laha')
   OR (project_id = 'org.apache:collections' AND author = 'Gary D. Gregory')
   OR (project_id = 'org.apache:collections' AND author = 'Geir Magnusson Jr')
   OR (project_id = 'org.apache:collections' AND author = 'James W. Carman')
   OR (project_id = 'org.apache:collections' AND author = 'Jason van Zyl')
   OR (project_id = 'org.apache:collections' AND author = 'Luc Maisonobe')
   OR (project_id = 'org.apache:collections' AND author = 'Matthew Hawthorne')
   OR (project_id = 'org.apache:collections' AND author = 'Matthew Jason Benson')
   OR (project_id = 'org.apache:commons-cli' AND author = 'Benedikt Ritter')
   OR (project_id = 'org.apache:commons-cli' AND author = 'No Author')
   OR (project_id = 'org.apache:commons-cli' AND author = 'Sebastian Bazley')
   OR (project_id = 'org.apache:commons-exec' AND author = 'Benedikt Ritter')
   OR (project_id = 'org.apache:commons-exec' AND author = 'Brett Porter')
   OR (project_id = 'org.apache:commons-fileupload' AND author = 'Simone Tripodi')
   OR (project_id = 'org.apache:commons-fileupload' AND author = 'Stephen Colebourne')
   OR (project_id = 'org.apache:commons-io' AND author = 'Gary D. Gregory')
   OR (project_id = 'org.apache:commons-io' AND author = 'Jochen Wiedmann')
   OR (project_id = 'org.apache:commons-io' AND author = 'Jukka Zitting')
   OR (project_id = 'org.apache:commons-io' AND author = 'Kristian Rosenvold')
   OR (project_id = 'org.apache:commons-io' AND author = 'Olivier Lamy')
   OR (project_id = 'org.apache:commons-io' AND author = 'Scott Sanders')
   OR (project_id = 'org.apache:commons-jelly' AND author = 'Paul Libbrecht')
   OR (project_id = 'org.apache:commons-jelly' AND author = 'Rodney Waldhoff')
   OR (project_id = 'org.apache:commons-jelly' AND author = 'Stephane Mor')
   OR (project_id = 'org.apache:commons-jexl' AND author = 'Christian Grobmeier')
   OR (project_id = 'org.apache:commons-jexl' AND author = 'Henri Yandell')
   OR (project_id = 'org.apache:commons-jexl' AND author = 'James Strachan')
   OR (project_id = 'org.apache:commons-jexl' AND author = 'Peter A Royal Jr')
   OR (project_id = 'org.apache:configuration' AND author = 'Dennis Kieselhorst')
   OR (project_id = 'org.apache:daemon' AND author = 'Jean-Frederic Clere')
   OR (project_id = 'org.apache:daemon' AND author = 'Mladen Turk')
   OR (project_id = 'org.apache:daemon' AND author = 'Sebastian Bazley')
   OR (project_id = 'org.apache:dbcp' AND author = 'Craig R. McClanahan')
   OR (project_id = 'org.apache:dbcp' AND author = 'Glenn L. Nielsen')
   OR (project_id = 'org.apache:dbutils' AND author = 'Bill Speirs')
   OR (project_id = 'org.apache:dbutils' AND author = 'Carl Franklin Hall')
   OR (project_id = 'org.apache:dbutils' AND author = 'Simone Tripodi')
   OR (project_id = 'org.apache:digester' AND author = 'Dirk Verbeeck')
   OR (project_id = 'org.apache:felix' AND author = 'Humberto Cervantes Maceda')
   OR (project_id = 'org.apache:felix' AND author = 'Rob Walker')
   OR (project_id = 'org.apache:hive' AND author = 'Gang Tim Liu')
   OR (project_id = 'org.apache:hive' AND author = 'Jianyong Dai')
   OR (project_id = 'org.apache:hive' AND author = 'Johan Oskarsson')
   OR (project_id = 'org.apache:hive' AND author = 'John Pullokkaran')
   OR (project_id = 'org.apache:hive' AND author = 'Joydeep Sensarma')
   OR (project_id = 'org.apache:hive' AND author = 'Nigel Daley')
   OR (project_id = 'org.apache:hive' AND author = 'Prasad Chakka')
   OR (project_id = 'org.apache:hive' AND author = 'Rui Li')
   OR (project_id = 'org.apache:hive' AND author = 'Siying Dong')
   OR (project_id = 'org.apache:httpclient' AND author = 'Francois-Xavier Bonnet')
   OR (project_id = 'org.apache:httpclient' AND author = 'Karl Wright')
   OR (project_id = 'org.apache:httpclient' AND author = 'Ortwin Glueck')
   OR (project_id = 'org.apache:httpclient' AND author = 'Sebastian Bazley')
   OR (project_id = 'org.apache:httpclient' AND author = 'asf-sync-process')
   OR (project_id = 'org.apache:httpcore' AND author = 'Gary D. Gregory')
   OR (project_id = 'org.apache:httpcore' AND author = 'asf-sync-process')
   OR (project_id = 'org.apache:jxpath' AND author = 'Emmanuel Bourg')
   OR (project_id = 'org.apache:jxpath' AND author = 'Matthew Jason Benson')
   OR (project_id = 'org.apache:jxpath' AND author = 'Stephen Colebourne')
   OR (project_id = 'org.apache:net' AND author = 'Henri Yandell')
   OR (project_id = 'org.apache:net' AND author = 'Stephen Colebourne')
   OR (project_id = 'org.apache:ognl' AND author = 'Antonio Petrelli')
   OR (project_id = 'org.apache:ognl' AND author = 'Lukasz Lenart')
   OR (project_id = 'org.apache:ognl' AND author = 'Olivier Lamy')
   OR (project_id = 'org.apache:santuario' AND author = 'Axl Mattheus')
   OR (project_id = 'org.apache:santuario' AND author = 'Erwin van der Koogh')
   OR (project_id = 'org.apache:thrift' AND author = 'David Reiss')
   OR (project_id = 'org.apache:thrift' AND author = 'Doug Cutting')
   OR (project_id = 'org.apache:thrift' AND author = 'Roger Meier')
   OR (project_id = 'org.apache:thrift' AND author = 'T Jake Luciani')
   OR (project_id = 'org.apache:thrift' AND author = 'Todd Lipcon')
   OR (project_id = 'org.apache:validator' AND author = 'Eitan Adler')
   OR (project_id = 'org.apache:validator' AND author = 'Ted Nathan Husted')
   OR (project_id = 'org.apache:vfs' AND author = 'Bernd Eckenfels')
   OR (project_id = 'org.apache:vfs' AND author = 'Henri Yandell')
   OR (project_id = 'org.apache:vfs' AND author = 'James Strachan')
   OR (project_id = 'org.apache:vfs' AND author = 'James W. Carman')
   OR (project_id = 'org.apache:vfs' AND author = 'Joerg Schaible')
   OR (project_id = 'org.apache:vfs' AND author = 'Niall Pemberton')
   OR (project_id = 'org.apache:vfs' AND author = 'Rahul Akolkar')
   OR (project_id = 'org.apache:zookeeper' AND author = 'Alexander Shraer')
   OR (project_id = 'org.apache:zookeeper' AND author = 'Camille Fournier')
   OR (project_id = 'org.apache:zookeeper' AND author = 'Michi Mutsuzaki')
   OR (project_id = 'org.apache:zookeeper' AND author = 'Raúl Gutiérrez Segalés');
